{{- if and .Values.otelCollector.enabled .Values.otelCollector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "adaptive.otelCollector.serviceAccount.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.otelCollector.selectorLabels" . | nindent 4 }}
  {{- with .Values.otelCollector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
