{{- if and .Values.otelCollector.enabled .Values.otelCollector.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "adaptive.otelCollector.role.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.otelCollector.selectorLabels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "adaptive.otelCollector.roleBinding.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.otelCollector.selectorLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "adaptive.otelCollector.serviceAccount.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "adaptive.otelCollector.role.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
