{{- if .Values.redis.install.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adaptive.redis.fullname" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.redis.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "adaptive.redis.selectorLabels" . | nindent 6}}
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adaptive.labels" . | nindent 8 }}
        {{- include "adaptive.redis.selectorLabels" . | nindent 8 }}
        {{- with .Values.redis.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- if .Values.redis.nodeSelector }}
      nodeSelector:
        {{- with .Values.redis.nodeSelector }}
        {{ toYaml . }}
        {{- end}}
      {{- end}}
      {{- if .Values.redis.tolerations }}
      tolerations:
      {{- with .Values.redis.tolerations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.port }}
              name: redis
          args: ["--aclfile", "/config/default.acl"]
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- if .Values.redis.extraEnvVars }}
          env:
          {{- range $key, $value := .Values.redis.extraEnvVars }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: redis-config
              mountPath: /config
      volumes:
        - name: redis-config
          configMap:
            name: {{ include "adaptive.redis.configMap.fullname" $ }}
{{- end }}
